version: "3.1"
services:
  server:
    image: springio/gs-spring-boot-docker
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/rest?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rest
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

networks:
  springmysql-net: