openapi: 3.0.2
info:
  title: "REST API"
  description: "EPAM's lab application"
  version: "1.0.0"
  contact:
    name: "username"
    url: "https://openweathermap.org/api"
    email: "test@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  url: "http://localhost:8080/"
  description: "Локальный сервер"
tags:
  - name: "clients"
    description: "Взаимодействие с клиентами"
paths:
  /clients:
    post:
      tags:
        - "Клиенты"
      summary: "Создание клиента"
      description: "Позволяет создать нового клиента"
      operationId: "create"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Создание entity клиента"
          required: true
          schema:
            $ref: "#/definitions/Clients"
      responses:
        default:
          description: "Операция успешна"
  /clients/{id}:
    get:
      tags:
        - "Клиенты"
      summary: "Нахождение клиента"
      description: "Возвращает клиента по его ID"
      operationId: "read"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Необходимо указать ID клиента"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Операция успешна"
          schema:
            $ref: "#/definitions/Clients"
        "400":
          description: "Неверный ID клиента"
        "404":
          description: "Клиент не найден"
    put:
      tags:
        - "Клиенты"
      summary: "Обновление данных клиента"
      description: "Обновляет клиента с заданным ID"
      operationId: "update"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID клиента для обновления"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/Clients"
      responses:
        "400":
          description: "Неверный ID клиента"
        "404":
          description: "Клиент не найден"
    delete:
      tags:
        - "Клиенты"
      summary: "Удаление клиента"
      description: "Удаляет клиента с заданным ID"
      operationId: "delete"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID клиента для удаления"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "400":
          description: "Неверный ID клиента"
        "404":
          description: "Клиент не найден"
definitions:
  Client:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      clientName:
        type: "string"
      phone:
        type: "string"
      orders:
        type: "array"
    xml:
      name: "Clients"
externalDocs:
  description: "Find out app on github"
  url: "https://github.com/panoffmaxim/restapi-practice"
